
workflows:
  ios-release:
    name: Shape 76 iPhone

    environment:
      node: 20
      xcode: latest

    scripts:
      - npm install
      - npm run build
      - npx cap add ios
      - npx cap sync ios
      - xcode-project build-ipa

    artifacts:
      - build/ios/ipa/*.ipa