workflows:
  ios-release:
    name: Shape 76 iPhone

    environment:
      xcode: latest
      node: 22

    scripts:
      - npm install
      - npm run build
      - npx cap sync ios

    ios_signing:
      distribution_type: development
      bundle_identifier: com.fernando.shape76

    artifacts:
      - build/ios/ipa/*.ipa